#!/usr/bin/env sh
set -eu

echo "Checking Rust formatting..."
cargo fmt --check

echo "Checking clippy for all binaries..."
cargo clippy --bins -- -D warnings

echo "Checking clippy for all binaries + power_measurement..."
cargo clippy --bins --features power_measurement -- -D warnings
